// GENERATED by scripts/sync-upstream-baseline.mjs — do not edit by hand.
//
// Offline snapshot of atomic-chat-conf/models/decision.json. The catalog
// registry falls back to it when the network and the cache both fail, so it
// deliberately carries real repos, revisions, byte counts and hashes.
// Regenerate with `make sync-upstream-baseline` after the catalog moves.
import type { DecisionCatalog } from './decision-catalog-registry'

export const BASELINE_DECISION_CATALOG: DecisionCatalog = {
  "schema_version": 1,
  "updated_at": "2026-10-01T12:00:00Z",
  "models": [
    {
      "id": "laya-multilingual",
      "name": "Laya Multilingual",
      "description": "Decision model for 100+ languages. Answers yes/no, choice and score questions about a text in one encoder pass.",
      "repo": "convaiinnovations/laya-multilingual",
      "revision": "e4e9ddf21a7b1903b7acffd8814ad4307bf63a67",
      "backbone": "mmBERT-base",
      "params": "322M",
      "languages": "multilingual",
      "context": 1024,
      "calibrated": false,
      "license": "apache-2.0",
      "default": true,
      "min_engine": "b10269-1.7.0",
      "gguf_cache_bytes": 658505728,
      "files": [
        {
          "path": "model.safetensors",
          "bytes": 643835514,
          "sha256": "9d628fd971b700382ac6f65920a86f149777b2e748e0c955fb3b19695aa8f204"
        },
        {
          "path": "rl_agent_config.json",
          "bytes": 472,
          "sha256": "25061739243b617ad88d1219ba6f8a9c86c5881ca28df024fa2d9b3b2fcc30c6"
        },
        {
          "path": "encoder/config.json",
          "bytes": 1938,
          "sha256": "83f6916d13ef0f556ac461f28308dc2bffa7ebeadee8ec9e2db5812020ea5bb4"
        },
        {
          "path": "tokenizer/tokenizer.json",
          "bytes": 34363188,
          "sha256": "609d8f4c067cd3950f88594c5a802616cea245823836ef5848ee4fc40aab5b6f"
        },
        {
          "path": "tokenizer/tokenizer_config.json",
          "bytes": 502,
          "sha256": "424b69444bf7b5809dc2cd2e36d0bd71b8055124dd24274d6db3c655d38205e7"
        },
        {
          "path": "README.md",
          "bytes": 9346,
          "sha256": "e85d16c3fe35fe7094ef51a7cfa81144a5cc07558e5faddcff753a8153e38a0b"
        }
      ]
    },
    {
      "id": "laya",
      "name": "Laya",
      "description": "English decision model with calibrated answers. Short texts, up to 512 tokens.",
      "repo": "convaiinnovations/laya",
      "revision": "55cf4c4ebb4ebe31b2550e8bdf3bd21b99753851",
      "backbone": "ModernBERT-large",
      "params": "421M",
      "languages": "en",
      "context": 512,
      "calibrated": true,
      "license": "apache-2.0",
      "min_engine": "b10269-1.7.0",
      "gguf_cache_bytes": 844103680,
      "files": [
        {
          "path": "model.safetensors",
          "bytes": 842609210,
          "sha256": "891102d372688fc2a094dac56a384bc537b87c63f21f9f3dac0be2b7cbc8d86c"
        },
        {
          "path": "rl_agent_config.json",
          "bytes": 745,
          "sha256": "ae287b56bbcf5f8c4f4541ae9dfd00c914c4c48b940b8398c3058af37ba92bbd"
        },
        {
          "path": "encoder/config.json",
          "bytes": 2083,
          "sha256": "bf3ab80598fdccf414855a2ce80f22859e4492d06ca8a62ddd1cfb63972f8979"
        },
        {
          "path": "tokenizer/tokenizer.json",
          "bytes": 3583228,
          "sha256": "6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30"
        },
        {
          "path": "tokenizer/tokenizer_config.json",
          "bytes": 308,
          "sha256": "50044de60daaa73df97d262e15a40d4faf0160e7d742df64b377877a1320dd12"
        },
        {
          "path": "README.md",
          "bytes": 23187,
          "sha256": "00355613796b3f5860b0d5b20392381d26580ec242e04a1fd150c7f116858602"
        }
      ]
    },
    {
      "id": "laya-typed-decisions",
      "name": "Laya Typed Decisions",
      "description": "English decision model with calibrated answers and a longer context, up to 1024 tokens.",
      "repo": "convaiinnovations/laya-typed-decisions",
      "revision": "1a793eb568e6718f15941d08f85432581df534e3",
      "backbone": "ModernBERT-large",
      "params": "421M",
      "languages": "en",
      "context": 1024,
      "calibrated": true,
      "license": "apache-2.0",
      "min_engine": "b10269-1.7.0",
      "gguf_cache_bytes": 844103680,
      "files": [
        {
          "path": "model.safetensors",
          "bytes": 842609220,
          "sha256": "4fa56de72383a9d3efa9cfa78955733c81b9fc8067a587ca4beb82c78107a24e"
        },
        {
          "path": "rl_agent_config.json",
          "bytes": 847,
          "sha256": "ebf0cd524d92342a6be5e48e9fca3d7c2babfb5a56ccd79d2171ef5d8c7f7be8"
        },
        {
          "path": "encoder/config.json",
          "bytes": 2084,
          "sha256": "5268d24ad3b77c8151de5dcb0762ba4391619aad9ab0bda33e36fb083cfeae6d"
        },
        {
          "path": "tokenizer/tokenizer.json",
          "bytes": 3583228,
          "sha256": "6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30"
        },
        {
          "path": "tokenizer/tokenizer_config.json",
          "bytes": 337,
          "sha256": "08d4cf3ac4dca381759441b85b91a6d40e688471dcd33d15d6649eb0a9a854d1"
        },
        {
          "path": "README.md",
          "bytes": 6343,
          "sha256": "83e67a995a70a9a9ef6cc1f8c68da654f11eee081c9bb14de07c37b08fcc3113"
        }
      ]
    }
  ]
}
