// GENERATED by scripts/sync-upstream-baseline.mjs — do not edit by hand.
//
// Offline snapshot of atomic-chat-conf/backends/sdcpp-manifest.json. The
// diffusion installer resolves the live manifest first and falls back to this
// when the network and the cache both fail. The tag here is NOT a pin — a live
// manifest on a newer tag is followed as-is.
import type { SdcppManifest } from './diffusion/install'

export const BASELINE_SDCPP_MANIFEST: SdcppManifest = {
  "tag_name": "master-883-137f740",
  "upstream_repo": "leejet/stable-diffusion.cpp",
  "assets": [
    {
      "backend": "macos-arm64",
      "name": "sd-master-137f740-bin-Darwin-macOS-26.6.2-arm64.zip",
      "sha256": "d850bc4eaa0a2254f0a44b10e1ce1ebf6b7dd866c3ea48a3a73246d49173212f",
      "size": 34194785
    },
    {
      "backend": "win-cuda12-x64",
      "name": "sd-master-137f740-bin-win-cuda12-x64.zip",
      "sha256": "d181b8a7be452dc74f2163893ec17edd960005c9f790382aef939e7bf93ab07f",
      "size": 330849525
    },
    {
      "backend": "win-rocm-7.14-x64",
      "name": "sd-master-137f740-bin-win-rocm-7.14.0-x64.zip",
      "sha256": "d541f7aa0d0046843dc35fecd79dbf808cf5af8bd6ab5c0d048dad9e9342c59d",
      "size": 192039488
    },
    {
      "backend": "win-vulkan-x64",
      "name": "sd-master-137f740-bin-win-vulkan-x64.zip",
      "sha256": "c76b8427d4dd4946f1f2e088512835550f7c6a17565cf2064ca7b656a6d7f7a6",
      "size": 31890985
    },
    {
      "backend": "win-cpu-x64",
      "name": "sd-master-137f740-bin-win-cpu-x64.zip",
      "sha256": "085713ca0e7da18ede7ebab63c2e2f0c6db8ca7417698a1eec2b099e8280b7b6",
      "size": 17140909
    },
    {
      "backend": "linux-vulkan-x64",
      "name": "sd-master-137f740-bin-Linux-Ubuntu-24.04-x86_64-vulkan.zip",
      "sha256": "4b65cfa5e7d4ced8fe43185b314bcba994413655e6273c78aeaaaaeab2ecec0f",
      "size": 38475898
    },
    {
      "backend": "linux-rocm-7.14-x64",
      "name": "sd-master-137f740-bin-Linux-Ubuntu-24.04-x86_64-rocm-7.14.0.zip",
      "sha256": "c3ed9cc94bbbc808a02c01cd3e07f60f84055e91b7f57e8aed528b7b06339645",
      "size": 258024162
    },
    {
      "backend": "linux-cpu-x64",
      "name": "sd-master-137f740-bin-Linux-Ubuntu-24.04-x86_64.zip",
      "sha256": "a09fde8b640c4f209f29e0db5f9cfcadc7f249bc9d57ace34d2d93cf2fbc465b",
      "size": 25352606
    },
    {
      "backend": "win-cudart-cu12",
      "name": "cudart-sd-bin-win-cu12-x64.zip",
      "sha256": "fe20366827d357c00797eebb58244dddab7fd9a348d70090c3871004c320f38d",
      "size": 563452046,
      "companion": true
    }
  ]
}
